In [2]:
import torch
import torch.nn as nn

import pprint
pp = pprint.PrettyPrinter()

In [2]:
list_of_lists = [
    [1,2,3],
    [4,5,6],
]
print(list_of_lists)

[[1, 2, 3], [4, 5, 6]]


In [3]:
data = torch.tensor(list_of_lists)
print(data)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
# Initializing a tensor
data = torch.tensor([
                     [0, 1],
                     [2, 3],
                     [4, 5]
                    ])
print(data)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [5]:
# Initializing a tensor with an explicit data type
# Notice the dots after the numbers, which specify that they're floats
data = torch.tensor([
                     [0, 1],
                     [2, 3],
                     [4, 5]
                    ], dtype=torch.float32)
print(data)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])


In [6]:
# Initializing a tensor with an explicit data type
# Notice the dots after the numbers, which specify that they're floats
data = torch.tensor([
                     [0.11111111, 1],
                     [2, 3],
                     [4, 5]
                    ], dtype=torch.float32)
print(data)

tensor([[0.1111, 1.0000],
        [2.0000, 3.0000],
        [4.0000, 5.0000]])


In [7]:
# Initializing a tensor with an explicit data type
# Notice the dots after the numbers, which specify that they're floats
data = torch.tensor([
                     [0.11111111, 1],
                     [2, 3],
                     [4, 5]
                    ])
print(data)

tensor([[0.1111, 1.0000],
        [2.0000, 3.0000],
        [4.0000, 5.0000]])


In [8]:
zeros = torch.zeros(2, 5)  # a tensor of all zeros
print(zeros)
zeros = torch.zeros(2, 5)  # a tensor of all zeros
print(zeros)
rr = torch.arange(1, 10) # range from [1, 10)
print(rr)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [9]:
a = torch.tensor([[1, 2], [2, 3], [4, 5]])      # (3, 2)
b = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])  # (2, 4)

print("A is", a)
print("B is", b)
print("The product is", a.matmul(b)) #(3, 4)
print("The other product is", a @ b) # +, -, *, @

A is tensor([[1, 2],
        [2, 3],
        [4, 5]])
B is tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
The product is tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])
The other product is tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])


In [10]:
matr_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matr_2d.shape)
print(matr_2d)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [11]:
rr = torch.arange(1, 16)
print("The shape is currently", rr.shape)
print("The contents are currently", rr)
print()
rr = rr.view(5, 3)
print("After reshaping, the shape is currently", rr.shape)
print("The contents are currently", rr)

The shape is currently torch.Size([15])
The contents are currently tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

After reshaping, the shape is currently torch.Size([5, 3])
The contents are currently tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


In [12]:
import numpy as np

# numpy.ndarray --> torch.Tensor:
arr = np.array([[1, 0, 5]])
data = torch.tensor(arr)
print("This is a torch.tensor", data)

# torch.Tensor --> numpy.ndarray:
new_arr = data.numpy()
print("This is a np.ndarray", new_arr)

This is a torch.tensor tensor([[1, 0, 5]])
This is a np.ndarray [[1 0 5]]


In [13]:
data = torch.arange(1, 36, dtype=torch.float32).reshape(5, 7)
print("Data is:", data)

# We can perform operations like *sum* over each row...
print("Taking the sum over rows:")
print(data.sum(dim=1)) #(5,)

# or over each column.
print("Taking thep sum over columns:")
print(data.sum(dim=0)) #(7,)

# Other operations are available:
print("Taking the stdev over rows:")
print(data.std(dim=1))

Data is: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19., 20., 21.],
        [22., 23., 24., 25., 26., 27., 28.],
        [29., 30., 31., 32., 33., 34., 35.]])
Taking the sum over rows:
tensor([ 28.,  77., 126., 175., 224.])
Taking thep sum over columns:
tensor([ 75.,  80.,  85.,  90.,  95., 100., 105.])
Taking the stdev over rows:
tensor([2.1602, 2.1602, 2.1602, 2.1602, 2.1602])


In [14]:
data = torch.arange(1, 7, dtype=torch.float32).reshape(1, 2, 3)
print(data)
print(data.sum(dim=0).sum(dim=0))
print(data.sum(dim=0).sum(dim=0).shape)

tensor([[[1., 2., 3.],
         [4., 5., 6.]]])
tensor([5., 7., 9.])
torch.Size([3])


In [15]:
data.sum()

tensor(21.)

In [17]:
data1 = torch.tensor(
    [
        [1,2.2,9.6],
        [4,-7.2,6.3]
    ])
print(data1)
print(data1.mean(dim=1))
print(data1.mean(dim=0))

tensor([[ 1.0000,  2.2000,  9.6000],
        [ 4.0000, -7.2000,  6.3000]])
tensor([4.2667, 1.0333])
tensor([ 2.5000, -2.5000,  7.9500])


In [18]:
# Initialize an example tensor
x = torch.Tensor([
                  [[1, 2], [3, 4]],
                  [[5, 6], [7, 8]],
                  [[9, 10], [11, 12]]
                 ])
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [19]:
x.shape

torch.Size([3, 2, 2])

In [20]:
x[0]

tensor([[1., 2.],
        [3., 4.]])

In [21]:
x[:,0]

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])

In [22]:
x[:, 0, 0]

tensor([1., 5., 9.])

In [23]:
x[:, :, :]

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [26]:
# Let's access the 0th and 1st elements, each twice
# same as stacking x[0], x[0], x[1], x[1]
i = torch.tensor([0, 0, 1, 1])
print(x[i])
print(x.shape)
print(x[i].shape)


tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]],

        [[5., 6.],
         [7., 8.]]])
torch.Size([3, 2, 2])
torch.Size([4, 2, 2])


In [28]:
i = torch.tensor([1, 2])
j = torch.tensor([0])
print(x[i])
print(x[i, j])
print(x[i, j].shape)

tensor([[[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
tensor([[ 5.,  6.],
        [ 9., 10.]])
torch.Size([2, 2])


In [36]:
print(x[0, 0, 0])
print(x[0][0][0])
print(x[torch.tensor([0,0,1,1])])
print(x[0, 0, 0].item())

tensor(1.)
tensor(1.)
tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]],

        [[5., 6.],
         [7., 8.]]])
1.0


In [38]:
y = torch.tensor([[1,2.2,9.6],[4,-7.2,6.3]])
print("first column:", y[:,0])
print("first row:", y[0,:])

first column: tensor([1., 4.])
first row: tensor([1.0000, 2.2000, 9.6000])


In [ ]:
x = torch.tensor([2.], requires_grad=True)
pp.pprint(x.grad)

None


In [4]:
y = x * x * 3
y.backward()
pp.pprint(x.grad)

tensor([12.])


In [7]:
z = x * x * 3
z.backward()
pp.pprint(x.grad)

tensor([48.])


In [8]:
x.grad = None
z = x * x * 3 # 3x^2
z.backward()
# y = x * x * 3
pp.pprint(x.grad)

tensor([12.])


In [9]:
z = x * x * 3 # 3x^2
z.backward()
# y = x * x * 3
pp.pprint(x.grad)

tensor([24.])


In [10]:
import torch.nn as nn

In [13]:
input = torch.ones(2,3,4)

linear = nn.Linear(4,2)
linear_output = linear(input)
linear_output

tensor([[[ 0.5037, -0.1262],
         [ 0.5037, -0.1262],
         [ 0.5037, -0.1262]],

        [[ 0.5037, -0.1262],
         [ 0.5037, -0.1262],
         [ 0.5037, -0.1262]]], grad_fn=<ViewBackward0>)

In [20]:
print(type(linear))
print(linear)

<class 'torch.nn.modules.linear.Linear'>
Linear(in_features=4, out_features=2, bias=True)


In [14]:
linear_output.shape

torch.Size([2, 3, 2])

In [15]:
list(linear.parameters())

[Parameter containing:
 tensor([[-0.0197,  0.4592,  0.1548, -0.2074],
         [-0.1812,  0.2551,  0.1601, -0.2636]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1168, -0.0966], requires_grad=True)]

In [16]:
linear_output

tensor([[[ 0.5037, -0.1262],
         [ 0.5037, -0.1262],
         [ 0.5037, -0.1262]],

        [[ 0.5037, -0.1262],
         [ 0.5037, -0.1262],
         [ 0.5037, -0.1262]]], grad_fn=<ViewBackward0>)

In [17]:
sigmoid = nn.Sigmoid()
output = sigmoid(linear_output)
output

tensor([[[0.6233, 0.4685],
         [0.6233, 0.4685],
         [0.6233, 0.4685]],

        [[0.6233, 0.4685],
         [0.6233, 0.4685],
         [0.6233, 0.4685]]], grad_fn=<SigmoidBackward0>)

In [18]:
block = nn.Sequential(
    nn.Linear(4,2),
    nn.Sigmoid()
)

input = torch.ones(2,3,4)
output = block(input)
output

tensor([[[0.7406, 0.4057],
         [0.7406, 0.4057],
         [0.7406, 0.4057]],

        [[0.7406, 0.4057],
         [0.7406, 0.4057],
         [0.7406, 0.4057]]], grad_fn=<SigmoidBackward0>)

In [22]:
class MultilayerPerceptron(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(MultilayerPerceptron, self).__init__()

        self.input_size = input_size
        self.hidden_size = hidden_size

        self.model = nn.Sequential(
            nn.Linear(self.input_size, self.hidden_size),
            nn.ReLU(),
            nn.Linear(self.hidden_size, self.input_size),
            nn.Sigmoid()
        )

    def forward(self, x):
        output = self.model(x)
        return output

In [23]:
class MultilayerPerceptron(nn.Module):

  def __init__(self, input_size, hidden_size):
    # Call to the __init__ function of the super class
    super(MultilayerPerceptron, self).__init__()

    # Bookkeeping: Saving the initialization parameters
    self.input_size = input_size
    self.hidden_size = hidden_size

    # Defining of our layers
    self.linear = nn.Linear(self.input_size, self.hidden_size)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(self.hidden_size, self.input_size)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    linear = self.linear(x)
    relu = self.relu(linear)
    linear2 = self.linear2(relu)
    output = self.sigmoid(linear2)
    return output

In [24]:
input = torch.randn(2,5)
model = MultilayerPerceptron(5,3)
model(input)

tensor([[0.6285, 0.5904, 0.4279, 0.6261, 0.5062],
        [0.6570, 0.5214, 0.4852, 0.5645, 0.4897]], grad_fn=<SigmoidBackward0>)

In [29]:
print(list(model.named_parameters()))
print()
print(list(model.parameters()))

[('linear.weight', Parameter containing:
tensor([[-0.0388,  0.0115, -0.0477,  0.1746,  0.1755],
        [ 0.4141,  0.1442,  0.2548,  0.2176,  0.1399],
        [ 0.1061,  0.3076, -0.3460, -0.0771, -0.1328]], requires_grad=True)), ('linear.bias', Parameter containing:
tensor([-0.2947,  0.2688, -0.1563], requires_grad=True)), ('linear2.weight', Parameter containing:
tensor([[ 0.3960,  0.2049,  0.0158],
        [-0.0081, -0.3582, -0.2752],
        [ 0.1608,  0.2007,  0.4437],
        [-0.4196, -0.2723, -0.3767],
        [ 0.3059, -0.3655,  0.5756]], requires_grad=True)), ('linear2.bias', Parameter containing:
tensor([ 0.4808,  0.4444, -0.3345,  0.5754,  0.1053], requires_grad=True))]

[Parameter containing:
tensor([[-0.0388,  0.0115, -0.0477,  0.1746,  0.1755],
        [ 0.4141,  0.1442,  0.2548,  0.2176,  0.1399],
        [ 0.1061,  0.3076, -0.3460, -0.0771, -0.1328]], requires_grad=True), Parameter containing:
tensor([-0.2947,  0.2688, -0.1563], requires_grad=True), Parameter containing:

In [26]:
import torch.optim as optim

In [27]:
y = torch.ones(10,5)
x = y + torch.rand_like(y)
x

tensor([[1.2167, 1.5183, 1.0970, 1.6182, 1.3536],
        [1.2959, 1.5605, 1.9769, 1.9246, 1.8379],
        [1.2793, 1.4829, 1.8751, 1.1469, 1.5803],
        [1.2954, 1.9877, 1.2683, 1.6825, 1.8363],
        [1.8911, 1.6380, 1.7866, 1.1930, 1.8506],
        [1.5159, 1.8318, 1.1368, 1.4803, 1.1922],
        [1.1193, 1.0035, 1.8189, 1.9178, 1.2034],
        [1.5701, 1.6579, 1.1957, 1.0696, 1.2776],
        [1.7430, 1.7812, 1.0915, 1.8182, 1.1967],
        [1.9675, 1.1748, 1.6653, 1.4112, 1.2487]])

In [30]:
model = MultilayerPerceptron(5,3)
adam = optim.Adam(model.parameters(), lr = 1e-1)
loss_function = nn.MSELoss()
y_pred = model(x)
loss_function(y_pred, y).item()

0.24385084211826324

In [34]:
n_epoch = 10

for epoch in range(n_epoch):
    adam.zero_grad()
    y_pred = model(x)
    loss = loss_function(y_pred, y)
    print(f"Epoch {epoch}: traing loss: {loss}")
    loss.backward()
    adam.step()

Epoch 0: traing loss: 8.823235544963559e-12
Epoch 1: traing loss: 6.666312033637434e-12
Epoch 2: traing loss: 5.2000361482062996e-12
Epoch 3: traing loss: 4.100115646304969e-12
Epoch 4: traing loss: 3.287823355582753e-12
Epoch 5: traing loss: 2.697788607092244e-12
Epoch 6: traing loss: 2.2538416445672116e-12
Epoch 7: traing loss: 1.903401915248626e-12
Epoch 8: traing loss: 1.641069550216423e-12
Epoch 9: traing loss: 1.460023183082193e-12


In [35]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.0741, -0.0130, -0.2577, -0.0466, -0.0935],
         [ 1.6345,  0.7501,  1.0744,  1.1326,  1.6133],
         [-0.0517, -0.1586,  0.2424, -0.1119, -0.4343]], requires_grad=True),
 Parameter containing:
 tensor([-0.0905,  1.4757, -0.1595], requires_grad=True),
 Parameter containing:
 tensor([[ 0.0715,  1.2232,  0.4787],
         [-0.3993,  1.4550, -0.2162],
         [ 0.4664,  1.0918,  0.2562],
         [-0.1894,  1.5787,  0.0466],
         [-0.0186,  1.4494, -0.4334]], requires_grad=True),
 Parameter containing:
 tensor([1.0923, 0.7200, 1.7633, 0.4779, 1.2917], requires_grad=True)]

In [36]:
y_pred = model(x)
y_pred

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]], grad_fn=<SigmoidBackward0>)

In [37]:
x2 = y + torch.randn_like(y)
y_pred = model(x2)
y_pred

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.9999, 1.0000, 0.9999, 1.0000, 1.0000],
        [0.9997, 0.9999, 0.9997, 0.9999, 0.9999],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.9999, 1.0000, 0.9999, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.9997, 0.9999, 0.9997, 0.9999, 0.9999]], grad_fn=<SigmoidBackward0>)

In [38]:
# Our raw data, which consists of sentences
corpus = [
          "We always come to Paris",
          "The professor is from Australia",
          "I live in Stanford",
          "He comes from Taiwan",
          "The capital of Turkey is Ankara"
         ]

In [39]:
def preprocess_sentence(sentence):
    return sentence.lower().split()

train_sentences = [preprocess_sentence(sent) for sent in corpus]
train_sentences

[['we', 'always', 'come', 'to', 'paris'],
 ['the', 'professor', 'is', 'from', 'australia'],
 ['i', 'live', 'in', 'stanford'],
 ['he', 'comes', 'from', 'taiwan'],
 ['the', 'capital', 'of', 'turkey', 'is', 'ankara']]

In [40]:
# Set of locations that appear in our corpus
locations = set(["australia", "ankara", "paris", "stanford", "taiwan", "turkey"])

# Our train labels
train_labels = [[1 if word in locations else 0 for word in sent] for sent in train_sentences]
train_labels

[[0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 1],
 [0, 0, 0, 1],
 [0, 0, 0, 1, 0, 1]]

In [41]:
vocabulary = set(w for s in train_sentences for w in s)
vocabulary

{'always',
 'ankara',
 'australia',
 'capital',
 'come',
 'comes',
 'from',
 'he',
 'i',
 'in',
 'is',
 'live',
 'of',
 'paris',
 'professor',
 'stanford',
 'taiwan',
 'the',
 'to',
 'turkey',
 'we'}

In [43]:
vocabulary.add("<unk>")
vocabulary.add("<pad>")

In [44]:
def pad_window(sentence, window_size, pad_token="<pad>"):
    window = [pad_token] * window_size
    return window + sentence + window

window_size = 2
pad_window(train_sentences[0], window_size=window_size)

['<pad>', '<pad>', 'we', 'always', 'come', 'to', 'paris', '<pad>', '<pad>']

In [45]:
ix_to_word = sorted(list(vocabulary))
word_to_ix = {word: ind for ind, word in enumerate(ix_to_word)}
word_to_ix

{'<pad>': 0,
 '<unk>': 1,
 'always': 2,
 'ankara': 3,
 'australia': 4,
 'capital': 5,
 'come': 6,
 'comes': 7,
 'from': 8,
 'he': 9,
 'i': 10,
 'in': 11,
 'is': 12,
 'live': 13,
 'of': 14,
 'paris': 15,
 'professor': 16,
 'stanford': 17,
 'taiwan': 18,
 'the': 19,
 'to': 20,
 'turkey': 21,
 'we': 22}

In [46]:
ix_to_word[1]

'<unk>'

In [49]:
def convert_token_to_indices(sentence, word_to_ix):
    indics = []
    for token in sentence:
        if token in word_to_ix:
            index = word_to_ix[token]
        else:
            index = word_to_ix["<unk>"]
        indics.append(index)
    return indics

def _convert_token_to_indices(sentence, word_to_ix):
    return [word_to_ix.get(token, word_to_ix["<unk>"]) for token in sentence]

# Show an example
example_sentence = ["we", "always", "come", "to", "kuwait"]
example_indices = convert_token_to_indices(example_sentence, word_to_ix)
restored_example = [ix_to_word[ind] for ind in example_indices]

print(f"Original sentence is: {example_sentence}")
print(f"Going from words to indices: {example_indices}")
print(f"Going from indices to words: {restored_example}")

Original sentence is: ['we', 'always', 'come', 'to', 'kuwait']
Going from words to indices: [22, 2, 6, 20, 1]
Going from indices to words: ['we', 'always', 'come', 'to', '<unk>']


In [50]:
# Converting our sentences to indices
example_padded_indices = [convert_token_to_indices(s, word_to_ix) for s in train_sentences]
example_padded_indices

[[22, 2, 6, 20, 15],
 [19, 16, 12, 8, 4],
 [10, 13, 11, 17],
 [9, 7, 8, 18],
 [19, 5, 14, 21, 12, 3]]

In [52]:
print(len(vocabulary))

23


In [55]:
embedding_dim = 5
embeds = nn.Embedding(len(vocabulary), embedding_dim)

list(embeds.parameters())

[Parameter containing:
 tensor([[ 9.3759e-01,  9.0246e-01,  2.4444e+00, -6.1161e-01, -7.8093e-01],
         [ 1.4826e+00, -1.0756e-01, -5.5413e-01, -1.8498e-01,  5.4926e-01],
         [-2.1009e-01,  6.7790e-01, -8.5876e-01,  1.3775e+00, -4.5351e-02],
         [ 2.0134e-01,  3.9017e-01, -5.1636e-01,  1.5398e+00,  1.0090e+00],
         [-7.9841e-01,  7.0264e-01,  5.6423e-02,  1.8708e-01,  3.9480e-02],
         [ 2.1029e-01,  7.2969e-01, -9.0378e-01,  1.0737e-01, -2.4598e-01],
         [-6.7668e-01, -1.9856e+00,  5.8227e-01,  1.4365e+00, -1.0449e-01],
         [ 9.6278e-01,  1.3199e+00,  2.7257e-01,  1.0458e+00,  5.1026e-02],
         [-2.0672e-01,  4.1953e-01, -9.5046e-01, -3.2168e-02, -3.3976e-01],
         [-2.7776e-02, -4.9862e-01,  3.2823e-01, -2.2483e+00,  4.1543e-01],
         [ 1.0578e+00,  4.9205e-01,  4.4932e-02,  1.7073e-01,  9.1031e-01],
         [-1.8576e+00,  2.0170e-01, -6.5142e-01,  6.8126e-01, -1.3751e-01],
         [-5.9279e-01,  6.1997e-01, -1.4548e+00, -7.6426e-02,  7.

In [57]:
index = word_to_ix["paris"]
index_tensor = torch.tensor(index, dtype=torch.long)
paris_embed = embeds(index_tensor)
paris_embed


tensor([-2.6343,  0.4302,  0.0391, -0.1735,  1.3368],
       grad_fn=<EmbeddingBackward0>)

In [58]:
# We can also get multiple embeddings at once
index_paris = word_to_ix["paris"]
index_ankara = word_to_ix["ankara"]
indices = [index_paris, index_ankara]
indices_tensor = torch.tensor(indices, dtype=torch.long)
embeddings = embeds(indices_tensor)
embeddings

tensor([[-2.6343,  0.4302,  0.0391, -0.1735,  1.3368],
        [ 0.2013,  0.3902, -0.5164,  1.5398,  1.0090]],
       grad_fn=<EmbeddingBackward0>)

In [70]:
from torch.utils.data import DataLoader
from functools import partial

def custom_collate_fn(batch, window_size, word_to_ix):
    x, y = zip(*batch)

    # 1. win pad 句子
    def pad_window(sentence, window_size, pad_token="<pad>"):
        window = [pad_token] * window_size
        return window + sentence + window

    x = [pad_window(s, window_size=window_size) for s in x]

    # 2. 转换成索引，拿到embeding
    def convert_token_to_indices(sentence, word_to_ix):
        return [word_to_ix.get(token, word_to_ix["<unk>"]) for token in sentence]

    x = [convert_token_to_indices(s, word_to_ix) for s in x]

    # 3. pad 标签,输入
    pad_token_ix = word_to_ix["<pad>"]
    x = [torch.LongTensor(x_i) for x_i in x]
    x_padded = nn.utils.rnn.pad_sequence(x, batch_first=True, padding_value=pad_token_ix)

    lengths = [len(label) for label in y]
    lengths = torch.LongTensor(lengths)

    y = [torch.LongTensor(y_i) for y_i in y]
    y_padded = nn.utils.rnn.pad_sequence(y, batch_first=True, padding_value=0)

    return x_padded, y_padded, lengths



In [69]:
pad_token_ix = word_to_ix["<pad>"]
ex = [torch.tensor(x_i) for x_i in example_padded_indices]
ex_padded = nn.utils.rnn.pad_sequence(ex, batch_first=False, padding_value=pad_token_ix)
print(ex[0].shape)
print(ex_padded)
print(ex_padded.shape)

torch.Size([5])
tensor([[22, 19, 10,  9, 19],
        [ 2, 16, 13,  7,  5],
        [ 6, 12, 11,  8, 14],
        [20,  8, 17, 18, 21],
        [15,  4,  0,  0, 12],
        [ 0,  0,  0,  0,  3]])
torch.Size([6, 5])


In [62]:
from torch.nn.utils.rnn import pad_sequence
a = torch.ones(25, 300)
b = torch.ones(22, 300)
c = torch.ones(15, 300)
pad_sequence([a, b, c]).size()

torch.Size([25, 3, 300])

In [74]:
def _custom_collate_fn(batch, window_size, word_to_ix):
  # Prepare the datapoints
  x, y = zip(*batch)
  x = [pad_window(s, window_size=window_size) for s in x]
  x = [convert_token_to_indices(s, word_to_ix) for s in x]

  # Pad x so that all the examples in the batch have the same size
  pad_token_ix = word_to_ix["<pad>"]
  x = [torch.LongTensor(x_i) for x_i in x]
  x_padded = nn.utils.rnn.pad_sequence(x, batch_first=True, padding_value=pad_token_ix)

  # Pad y and record the length
  lengths = [len(label) for label in y]
  lengths = torch.LongTensor(lengths)
  y = [torch.LongTensor(y_i) for y_i in y]
  y_padded = nn.utils.rnn.pad_sequence(y, batch_first=True, padding_value=0)

  return x_padded, y_padded, lengths

In [75]:
data = list(zip(train_sentences, train_labels))
batch_size = 2
shuffle = True
window_size = 2
collate_fn = partial(custom_collate_fn, window_size = window_size, word_to_ix = word_to_ix)

loader = DataLoader(data, batch_size=batch_size, shuffle=shuffle, collate_fn=collate_fn)

counter = 0
for batched_x, batched_y, batched_lengths in loader:
    print(f"Iteration {counter}")
    print("Batched Input:")
    print(batched_x)
    print("Batched Labels:")
    print(batched_y)
    print("Batched Lengths:")
    print(batched_lengths)
    print("")
    counter += 1 

Iteration 0
Batched Input:
tensor([[ 0,  0, 10, 13, 11, 17,  0,  0,  0],
        [ 0,  0, 19, 16, 12,  8,  4,  0,  0]])
Batched Labels:
tensor([[0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])
Batched Lengths:
tensor([4, 5])

Iteration 1
Batched Input:
tensor([[ 0,  0, 19,  5, 14, 21, 12,  3,  0,  0],
        [ 0,  0,  9,  7,  8, 18,  0,  0,  0,  0]])
Batched Labels:
tensor([[0, 0, 0, 1, 0, 1],
        [0, 0, 0, 1, 0, 0]])
Batched Lengths:
tensor([6, 4])

Iteration 2
Batched Input:
tensor([[ 0,  0, 22,  2,  6, 20, 15,  0,  0]])
Batched Labels:
tensor([[0, 0, 0, 0, 1]])
Batched Lengths:
tensor([5])



In [80]:
print(data)
batch_ = data[0:2]
x, y = zip(*batch_)
print(x)
print(y)

[(['we', 'always', 'come', 'to', 'paris'], [0, 0, 0, 0, 1]), (['the', 'professor', 'is', 'from', 'australia'], [0, 0, 0, 0, 1]), (['i', 'live', 'in', 'stanford'], [0, 0, 0, 1]), (['he', 'comes', 'from', 'taiwan'], [0, 0, 0, 1]), (['the', 'capital', 'of', 'turkey', 'is', 'ankara'], [0, 0, 0, 1, 0, 1])]
(['we', 'always', 'come', 'to', 'paris'], ['the', 'professor', 'is', 'from', 'australia'])
([0, 0, 0, 0, 1], [0, 0, 0, 0, 1])


In [76]:
# Print the original tensor
print(f"Original Tensor: ")
print(batched_x)
print("")

# Create the 2 * 2 + 1 chunks
chunk = batched_x.unfold(1, window_size*2 + 1, 1)
print(f"Windows: ")
print(chunk)

Original Tensor: 
tensor([[ 0,  0, 22,  2,  6, 20, 15,  0,  0]])

Windows: 
tensor([[[ 0,  0, 22,  2,  6],
         [ 0, 22,  2,  6, 20],
         [22,  2,  6, 20, 15],
         [ 2,  6, 20, 15,  0],
         [ 6, 20, 15,  0,  0]]])


In [83]:
class WordWindowClassifier(nn.Module):
    def __init__(self, hyperparameters, vocab_size, pad_ix=0):
        super(WordWindowClassifier, self).__init__()

        self.window_size = hyperparameters["window_size"]
        self.embed_dim = hyperparameters["embed_dim"]
        self.hidden_dim = hyperparameters["hidden_dim"]
        self.freeze_embeddings = hyperparameters["freeze_embeddings"]

        self.embeds = nn.Embedding(vocab_size, self.embed_dim, padding_idx=pad_ix)
        if self.freeze_embeddings:
            self.embed_layer.weight.requires_grad = False

        full_window_size = 2 * window_size + 1
        self.hidden_layer = nn.Sequential(
            nn.Linear(full_window_size * self.embed_dim, self.hidden_dim),
            nn.Tanh()
        )

        self.output_layer = nn.Linear(self.hidden_dim, 1)
        self.probabilities = nn.Sigmoid()

    def forward(self, inputs):
        """
        Let B:= batch_size
            L:= window-padded sentence length
            D:= self.embed_dim
            S:= self.window_size
            H:= self.hidden_dim

        inputs: a (B, L) tensor of token indices
        """ 
        B, L = inputs.size()

        # input B*L -> B*N*(2n+1)
        token_windows = inputs.unfold(1, 2*self.window_size+1, 1)
        _, adjusted_length, _ = token_windows.size()

        assert token_windows.size() == (B, adjusted_length, 2*self.window_size+1)

        # B*N*(2n+1) -> B*N*(2n+1)*embed_dim
        embedded_windows = self.embeds(token_windows)
        embedded_windows = embedded_windows.view(B, adjusted_length, -1)

        # B,N,(2n+1)d -> B, N, H
        layer_1 = self.hidden_layer(embedded_windows)

        # B,N,H -> B,N,1
        output = self.output_layer(layer_1)

        output = self.probabilities(output)
        output = output.view(B,-1)

        return output

In [84]:
# Prepare the data
data = list(zip(train_sentences, train_labels))
batch_size = 2
shuffle = True
window_size = 2
collate_fn = partial(custom_collate_fn, window_size=window_size, word_to_ix=word_to_ix)

# Instantiate a DataLoader
loader = DataLoader(data, batch_size=batch_size, shuffle=shuffle, collate_fn=collate_fn)

# Initialize a model
# It is useful to put all the model hyperparameters in a dictionary
model_hyperparameters = {
    "batch_size": 4,
    "window_size": 2,
    "embed_dim": 25,
    "hidden_dim": 25,
    "freeze_embeddings": False,
}

vocab_size = len(word_to_ix)
model = WordWindowClassifier(model_hyperparameters, vocab_size)

# Define an optimizer
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Define a loss function, which computes to binary cross entropy loss
def loss_function(batch_outputs, batch_labels, batch_lengths):
    # Calculate the loss for the whole batch
    bceloss = nn.BCELoss()
    loss = bceloss(batch_outputs, batch_labels.float())

    # Rescale the loss. Remember that we have used lengths to store the
    # number of words in each training example
    loss = loss / batch_lengths.sum().float()

    return loss

In [85]:
# Function that will be called in every epoch
def train_epoch(loss_function, optimizer, model, loader):

  # Keep track of the total loss for the batch
  total_loss = 0
  for batch_inputs, batch_labels, batch_lengths in loader:
    # Clear the gradients
    optimizer.zero_grad()
    # Run a forward pass
    outputs = model.forward(batch_inputs)
    # Compute the batch loss
    loss = loss_function(outputs, batch_labels, batch_lengths)
    # Calculate the gradients
    loss.backward()
    # Update the parameteres
    optimizer.step()
    total_loss += loss.item()

  return total_loss


# Function containing our main training loop
def train(loss_function, optimizer, model, loader, num_epochs=10000):

  # Iterate through each epoch and call our train_epoch function
  for epoch in range(num_epochs):
    epoch_loss = train_epoch(loss_function, optimizer, model, loader)
    if epoch % 100 == 0: print(epoch_loss)

In [86]:
num_epochs = 1000
train(loss_function, optimizer, model, loader, num_epochs=num_epochs)

0.25662674754858017
0.215030949562788
0.18453748524188995
0.1511201672255993
0.10017340444028378
0.08541299402713776
0.06998737528920174
0.05324980616569519
0.03951910976320505
0.03278742637485266


In [88]:
# Create test sentences
test_corpus = ["She comes from Paris"]
test_sentences = [s.lower().split() for s in test_corpus]
test_labels = [[0, 0, 0, 1]]

# Create a test loader
test_data = list(zip(test_sentences, test_labels))
batch_size = 1
shuffle = False
window_size = 2
collate_fn = partial(custom_collate_fn, window_size=2, word_to_ix=word_to_ix)
test_loader = torch.utils.data.DataLoader(test_data,
                                           batch_size=1,
                                           shuffle=False,
                                           collate_fn=collate_fn)

In [91]:
for test_instance, labels, _ in test_loader:
  outputs = model.forward(test_instance)
  print(labels)
  print(outputs)

tensor([[0, 0, 0, 1]])
tensor([[0.1015, 0.0546, 0.0487, 0.9757]], grad_fn=<ViewBackward0>)
